### ISSUE TITLE
Run with local extension

### ISSUE THREAD

**Issue by averrin** [wirepair/gcd#14]
When i use `--load-extension=ext_path` chrome opens but ignore
`target.Page.Navigate(url, "", "")` and other commands.
Can i fix it?

**Comment by wirepair** [comment]
Hello @averrin are you loading an extension that uses chrome.debug.*? Keep in mind extensions that use the debugger will not work with remote debugging as you can only attach a single debugger to an instance at a time.

**Comment by averrin** [comment]
No, its very simple extension thats disables CSP. If i can do it without extension this problem not so important.

**Comment by wirepair** [comment]
It would be nice to verify extensions are working properly, is the extension public, something I could download and test out locally?

**Comment by averrin** [comment]
I think this problem exists with any extension, but i use https://github.com/PhilGrayson/chrome-csp-disable and its simplified version without button. 
I tried code that modified responseHeaders but i cannot catch `Network.responseReceived` event.

**Comment by wirepair** [comment]
Yeah, I think the devtools developers just implemented the ability to modify requests: https://chromium.googlesource.com/chromium/src/+/6f5b3053ff11488b985c18e8d03472356e049fd5 but it may not be in the current protocol.json files yet (i'll try and update to the latest this weekend). In the meantime i'll test out this plugin and see if i can get it working.

**Comment by wirepair** [comment]
I just added a unit test to load that extension and it seems to work, as in I can still execute protocol commands such as Navigate, please see: https://github.com/wirepair/gcd/commit/bf4e133a6ec70a5e7f161b89bda4a6de406ecf71 is this what you were doing as well?

**Comment by wirepair** [comment]
I just updated to the latest protocol.json which supports network interception/modification. However I could not get it working on most browsers, only the latest dev builds seem to accept it. Let me know if this is enough information to close out this ticket for you.

**Comment by wirepair** [comment]
Since I've not heard a response on this for a while i'm closing it out, feel free to re-open if it is still an issue.
