### ISSUE TITLE
Change page viewport size

### ISSUE THREAD

**Issue by s3rj1k** [wirepair/gcd#18]
Please provide example with ability to screenshot view port with custom size.

**Comment by wirepair** [comment]
You mean like https://github.com/wirepair/autogcd/issues/13 ? While that is in my other project, it should be easy to reproduce for you in gcd as well.

**Comment by s3rj1k** [comment]
@wirepair added pull to autogcd
https://github.com/wirepair/autogcd/issues/25
to implement full sized screenshots

thanks for your help :)

**Comment by wirepair** [comment]
No problem!
