### ISSUE TITLE
chrome 67.0.3396.62 doesn't work

### ISSUE THREAD

**Issue by kwf2030** [wirepair/gcd#23]
I update my chrome to 67.0.3396.62 yestoday and it doesn't work.

Then I use gcdapigen to generate latest protocol.json and it produces errors:
```
error in domain: Accessibility
output\accessibility.go:100:1: expected declaration, found 'IDENT' children
output\accessibility.go:113:2: expected declaration, found 'if'
output\accessibility.go:140:2: expected declaration, found 'IDENT' v
2018/06/01 12:52:57 error waiting for gofmt to complete: exit status 2
```

**Comment by wirepair** [comment]
Hello @kwf2030,
Odd, it seemed to work for me (doing go build && gcdapigen -download). I've updated to 67.0.3396.62 in the master branch, please let me know if this is not working.

**Comment by kwf2030** [comment]
@wirepair it works, thanks for your work

**Comment by wirepair** [comment]
No problem! Glad that resolved it.
